name       : evemu
version    : 2.6.0
release    : 1
source     :
    - https://www.freedesktop.org/software/evemu/evemu-2.6.0.tar.xz : ed81dd4552ffeb92c346b47e56b249c67f1cb37d5b31fc073ea0ad4858ae3dcc
license    : LGPL-3.0
component  : programming
summary    : evemu - Kernel device emulation
description: |
    evemu records and replays device descriptions and events, making it possible to emulate input devices through the kernel's input system. Emulated devices are for most practical purposes indistinguishable from real devices.
builddeps  :
    - pkgconfig(libevdev)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
